### ISSUE TITLE
fa-flexible-layout is not updated on option change

### ISSUE THREAD

**Issue by oliviercooper** [Famous/famous-angular#184]
Hi,

I tried successfully the grid-layout example with "dimensions" option updated dynamically, as mentioned here : 
https://github.com/Famous/famous-angular/issues/132

When using the flexible-layout view and changing the "ratios" option in the same way, there's no updates.

Oliver

**Comment by Odonno** [comment]
It works for "fa-grid-layout" but the "fa-flexible-layout" does not update (refreshing ratios in options), any time...

**Comment by SuPenguin** [comment]
In the meanwhile, you could get the node via $famous.find and use the setRatios method. This way you can add a transition effect via the "transition" object into fa-options.

```jade
fa-flexible-layout(id='flexible', fa-options='layout')
```

```javascript
$scope.layout : {
         ratios: [3,1]
         transition: {
            curve: 'easeOut',
            duration: 200
          }
}

$scope.changeRatios = ()->
         $famous.find('#flexible')[0].renderNode.setRatios([1,3])

```

**Comment by Odonno** [comment]
Oh yeah ! It works great !

But, there is another bug I don't know how to fix...

Indeed, when I left the page (from the "fa-flexible-layout" to any other), an error (see image) occurs. So, when I want to navigate to any page, the entirely app is "frozen", nothing respond anymore (even in the page)...

![capture](https://cloud.githubusercontent.com/assets/6053067/5695435/ecd1f58c-99a3-11e4-850f-3bda3ae78daa.PNG)

From this image, I suppose it's due to the fact children of fa-flexible-layout are removed but the parent item is still there (somewhere).
