### ISSUE TITLE
10 $digest() iterations reached. Aborting!

### ISSUE THREAD

**Issue by bampakoa** [Famous/famous-angular#302]
Hi,

I have tested the 0.5.0 version with emulators provided by Chrome Developer Tools and in some of these like : Google Nexus S, Samsung Galaxy Note and Samsung Galaxy Tab, I get the following error in the console window:

**Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!**

**Comment by zackbrown** [comment]
Hi @bampakoa — thank you for reporting this.  Are you running any particular application code when you get this error?  This error is commonly triggered by an angular-$watched function that returns a new object or a new array, e.g.  `$scope.watchMe = function(){ return [1,2,3] }`.  Since it is a new reference that will be returned each time the expression `[1,2,3]` is evaluated (i.e. `[1,2,3] !== [1,2,3]`), angular will consider the watched expression dirty upon each evaluation and will thereby fire another digest, and so on, and so on, until it stops itself at 10 iterations.  Angular offers the ability to watchCollection and to deep-watch (`$watch(expr, true)`) but IMO the best way to handle this kind of situation is to return a reference to an object/array that was initialized *outside* of the function that's being $watched, e.g. `var _myArray = [1,2,3]; $scope.watchMe = function() {return _myArray;}`

If you believe this is a library bug rather than an application bug, can you please share the code that is causing this by reproducing it in a CodePen?  Here is a template that handles the boilerplate: http://codepen.io/zackbrown/pen/yyVQje  Note that 0.6.0rc is used in the codepen, which is currently master on github, i.e. not 0.5.0.

**Comment by jordanpapaleo** [comment]
Hi @bampakoa 

Can you please provide an update on this?  Thanks - Jordan

**Comment by jordanpapaleo** [comment]
I am going to close this.  Please reopen it if it is still an issue.  Thanks - Jordan

**Comment by bampakoa** [comment]
Hi @jordanpapaleo,

Sorry about the delay but I was quite busy the last days.

I made some tests and found that the problem consists when using **fa-click** in **fa-surface** to navigate to another route in my app, using **$window.location.href**. Below is the code:

    <fa-surface fa-click="go()">
          ...
    </fa-surface>

     $scope.go = function(){
          $window.location.href= "#/test";
     }

**Comment by jordanpapaleo** [comment]
Hi @bampakoa -

So fa-click is now depracated.  Please try using ng-click and let me know how that works for you.

Thanks,

Jordanj

**Comment by bampakoa** [comment]
Hi @jordanpapaleo 

The problem persists even if using the **ng-click**. May be, there is something wrong with the **router**. I would like to mention again that the problem appears only on specific emulators (provided by Google Developer Tools) such as Google Nexus S, Samsung Galaxy Note.

Thanks again

**Comment by jordanpapaleo** [comment]
I'd love to help with this.  Please create a [codepen](http://codepen.io/zackbrown/pen/yyVQje) so I can see what your are doing.

Thanks,

Jordan

**Comment by bampakoa** [comment]
Hi @jordanpapaleo 

My code pen is [this](http://codepen.io/bampakoa/pen/RNpOrB). It is probably a bug in the library because I was forced to change to 0.5.0 famous-angular so that I can reproduce it.

**Comment by jordanpapaleo** [comment]
Hi - 

So the issue is with how you are executing your change of route with ui-router.  Check out this [link](https://github.com/angular-ui/ui-router/wiki#activating-a-state).  You should not use $window.location.href = '#/test' but instead use $state.go('test) like in this [pen](http://codepen.io/anon/pen/emWxBe?editors=101).  

On a side note i noticed in your JS dependencies for your pen you are including ngRouter and ui-router.  This may just be my personal preference, but I would not recommend ever mixing the 2.  I have never seen it work :)

I hope this resolves your issue,

Jordan

**Comment by bampakoa** [comment]
Hi

That did the trick. Thank you very much.
