### ISSUE TITLE
bower version still references old versions of famous and angular

### ISSUE THREAD

**Issue by atgillette** [Famous/famous-angular#324]
When using bower install famous-angular, the bower.json still contains references to famous 0.3.0 and and angular.  Please rev these packages to the latest version.

**Comment by jordanpapaleo** [comment]
Hi @atgillette 

Thanks for catching this.  I had to do a patch tag bump to get it to work for some reason, which is odd because our bower.json was using angular 1.3.8 and famous 0.3.4.  So now if you bower install famous-angular you should get 0.5.1 which has newer versions of the dependencies. 

Thank you,

Jordan

**Comment by steveblue** [comment]
@jordanpapaleo minor version updates are more than welcome.

**Comment by atgillette** [comment]
Thanks @jordanpapaleo.
